version: '3.4'

services:
  graphql.users.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__UsersConnection=Server=db.users;Database=Users;User=sa;Password=test$$123;Integrated Security=False;MultipleActiveResultSets=True
    ports:
      - 80
      - 443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  graphql.photos.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__PhotosConnection=Server=db.photos;Database=Photos;User=sa;Password=test$$123;Integrated Security=False;MultipleActiveResultSets=True
    ports:
      - 80
      - 443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  graphql.stitching.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - GraphQL__UserServiceEndpoint=https://graphql.users.api
      - GraphQL__PhotoServiceEndpoint=https://graphql.photos.api
    ports:
      - 80
      - 443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  db.users:
    environment:
      - SA_PASSWORD=test$$123
      - ACCEPT_EULA=Y

  db.photos:
    environment:
      - SA_PASSWORD=test$$123
      - ACCEPT_EULA=Y