// <auto-generated />
using System;
using GraphQL.Photos.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GraphQL.Photos.Api.Migrations
{
    [DbContext(typeof(PhotosDbContext))]
    partial class PhotosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GraphQL.Photos.Api.Database.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnName("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnName("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 22, 12, 33, 55, 248, DateTimeKind.Local).AddTicks(7997),
                            Name = "Robak, Miklaś and Augustyniak",
                            Url = "https://korneli.com",
                            UserId = 7
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 2, 8, 20, 5, 56, 845, DateTimeKind.Local).AddTicks(5416),
                            Name = "Stolarski - Czech",
                            Url = "https://ofelia.net",
                            UserId = 6
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2019, 11, 4, 18, 51, 39, 624, DateTimeKind.Local).AddTicks(6163),
                            Name = "Adamus, Woliński and Czekaj",
                            Url = "https://wincenty.com.pl",
                            UserId = 9
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 2, 20, 13, 44, 17, 785, DateTimeKind.Local).AddTicks(1761),
                            Name = "Gwóźdź LLC",
                            Url = "https://samson.net",
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 9, 17, 19, 30, 59, 750, DateTimeKind.Local).AddTicks(6050),
                            Name = "Wasiak - Pawlicki",
                            Url = "http://regina.pl",
                            UserId = 10
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 4, 22, 22, 31, 14, 170, DateTimeKind.Local).AddTicks(3679),
                            Name = "Flak, Woś and Wieczorek",
                            Url = "https://harald.pl",
                            UserId = 9
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 9, 7, 14, 39, 34, 699, DateTimeKind.Local).AddTicks(2698),
                            Name = "Skowroński - Banasik",
                            Url = "http://dominik.com",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 5, 19, 0, 19, 53, 925, DateTimeKind.Local).AddTicks(2233),
                            Name = "Strzelczyk, Szewczyk and Przybysz",
                            Url = "http://sylwia.com",
                            UserId = 5
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2020, 1, 7, 20, 21, 16, 326, DateTimeKind.Local).AddTicks(1293),
                            Name = "Sobczyk - Broda",
                            Url = "http://apollo.net",
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 9, 4, 6, 3, 33, 446, DateTimeKind.Local).AddTicks(2661),
                            Name = "Kiełbasa, Maciąg and Bąkowski",
                            Url = "https://cecyliusz.org",
                            UserId = 7
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2019, 11, 6, 23, 24, 45, 287, DateTimeKind.Local).AddTicks(6751),
                            Name = "Ślusarczyk, Pietrzak and Kowalewski",
                            Url = "http://gertruda.com.pl",
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 5, 18, 22, 17, 55, 894, DateTimeKind.Local).AddTicks(266),
                            Name = "Janicki - Jagielski",
                            Url = "https://igor.org",
                            UserId = 5
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 12, 21, 19, 42, 29, 638, DateTimeKind.Local).AddTicks(9837),
                            Name = "Mielczarek, Kucharczyk and Kowalewski",
                            Url = "https://wanesa.pl",
                            UserId = 4
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2020, 5, 11, 1, 35, 35, 176, DateTimeKind.Local).AddTicks(1290),
                            Name = "Paszkowski, Zabłocki and Urbaniak",
                            Url = "https://paulina.com.pl",
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2020, 4, 22, 20, 20, 33, 699, DateTimeKind.Local).AddTicks(4357),
                            Name = "Stachowicz Inc",
                            Url = "http://arkadiusz.com.pl",
                            UserId = 10
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2020, 3, 5, 15, 15, 3, 149, DateTimeKind.Local).AddTicks(5053),
                            Name = "Markiewicz - Wiśniewski",
                            Url = "http://konstanty.net",
                            UserId = 6
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2020, 5, 20, 19, 5, 40, 421, DateTimeKind.Local).AddTicks(3372),
                            Name = "Kogut - Rogalski",
                            Url = "http://modest.com",
                            UserId = 6
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2020, 2, 3, 10, 22, 10, 627, DateTimeKind.Local).AddTicks(1615),
                            Name = "Wiśniewski, Trzciński and Banaś",
                            Url = "http://ewa.pl",
                            UserId = 2
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2019, 12, 14, 23, 53, 49, 311, DateTimeKind.Local).AddTicks(1565),
                            Name = "Sosnowski LLC",
                            Url = "http://maksym.com.pl",
                            UserId = 9
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2019, 10, 29, 21, 51, 39, 783, DateTimeKind.Local).AddTicks(6787),
                            Name = "Niewiadomski - Raczyński",
                            Url = "https://cyrus.net",
                            UserId = 3
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2020, 10, 3, 11, 9, 42, 864, DateTimeKind.Local).AddTicks(1299),
                            Name = "Jezierski LLC",
                            Url = "https://florian.net",
                            UserId = 4
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2020, 2, 28, 9, 55, 25, 73, DateTimeKind.Local).AddTicks(8036),
                            Name = "Kujawski - Dobrowolski",
                            Url = "https://serafin.org",
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2020, 10, 5, 6, 18, 49, 179, DateTimeKind.Local).AddTicks(1503),
                            Name = "Białkowski Group",
                            Url = "https://bibianna.com",
                            UserId = 9
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2020, 8, 15, 0, 49, 4, 973, DateTimeKind.Local).AddTicks(9812),
                            Name = "Koza, Stolarski and Kołodziejski",
                            Url = "https://alina.net",
                            UserId = 9
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2020, 2, 13, 8, 38, 5, 136, DateTimeKind.Local).AddTicks(916),
                            Name = "Trzeciak, Kozieł and Szeląg",
                            Url = "https://teodora.com.pl",
                            UserId = 4
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2020, 4, 12, 19, 39, 40, 630, DateTimeKind.Local).AddTicks(7044),
                            Name = "Wiącek, Kogut and Dudziński",
                            Url = "http://joanna.org",
                            UserId = 8
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2020, 2, 21, 4, 58, 58, 94, DateTimeKind.Local).AddTicks(7500),
                            Name = "Stanek Inc",
                            Url = "http://cyryl.pl",
                            UserId = 10
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2019, 12, 26, 14, 34, 36, 888, DateTimeKind.Local).AddTicks(3797),
                            Name = "Wasiak, Pietrzak and Niemiec",
                            Url = "https://emilia.org",
                            UserId = 8
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2020, 2, 25, 14, 29, 44, 514, DateTimeKind.Local).AddTicks(5690),
                            Name = "Iwanowski, Kaczorowski and Jagielski",
                            Url = "http://pantaleon.com",
                            UserId = 4
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2020, 8, 16, 6, 29, 4, 137, DateTimeKind.Local).AddTicks(3117),
                            Name = "Lipski LLC",
                            Url = "http://arystarch.com.pl",
                            UserId = 9
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
